name: flutter_gbk2utf8
description: A flutter package to convert gbk to utf-8. Fork of https://github.com/best-flutter/gbk2utf8 which seems to be abandoned.
version: 1.0.0
homepage: https://github.com/rohankandwal/-flutter_gbk2utf8.git

environment:
  sdk: ">=2.12.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: